name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.2.182.0/mac/vulkansdk-macos-1.2.182.0.dmg
        hdiutil attach vulkan-sdk.dmg
        vcpkg install glew:x64-osx glfw3:x64-osx utfcpp:x64-osx stb:x64-osx opengl:x64-osx
        vcpkg integrate install

    - name: Configure CMake
      run: |
        export CC=gcc-11
        export CXX=g++-11
        export VULKAN_SDK=/Volumes/vulkansdk-macos-1.2.182.0/macOS
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
