name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    env:
      VULKAN_SDK: ${{github.workspace}}/Vulkan
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        powershell (new-object System.Net.WebClient).DownloadFile('https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe','${{github.workspace}}/vulkan-sdk.exe')
        7z x ${{github.workspace}}/vulkan-sdk.exe -o${{github.workspace}}/Vulkan
        vcpkg install glew:x64-windows glfw3:x64-windows utfcpp:x64-windows stb:x64-windows opengl:x64-windows vulkan:x64-windows directx-headers:x64-windows
        vcpkg integrate install

    - name: Configure CMake
      run: cmake -G "Visual Studio 16 2019" -A x64 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
